# docker-compose.yml
version: "3.9"

services:
  app:
    ports:
      - '8000:80'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql-service
    links:
      - mysql-service
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-service
      - DB_PORT=3306
      - DB_DATABASE=tasks
      - DB_USERNAME=tasks
      - DB_PASSWORD=password

  mysql-service:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=tasks
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

volumes:
  dbdata:
